### ISSUE TITLE
SINQ doesn't compile under Xcode 7.3

### ISSUE THREAD

**Issue by marchy** [slazyk/SINQ#8]
Compiling the library under Xcode 7.3 (Beta 5) gives the following error:

SINQ.swift:27:20: Cannot invoke initializer for type 'AnySequence<_>' with an argument list of type '(S)'
    SINQ.swift:27:20: Overloads for 'AnySequence<_>' exist with these partially matching parameter lists: (S), (() -> G)

Given the iOS 9.3 release is days away this should probably be fixed immediately as apps using SINQ will start to break

**Comment by hazama-yuinyan** [comment]
I'm having trouble with this too.

I've found that [the language change](https://github.com/apple/swift-evolution/blob/master/proposals/0014-constrained-AnySequence.md) causes this problem, but I can't figure out a solution, or at least even a workaround for the problem.

I already tried to add constraints that mentioned in the above issue to the initializer functions, but it just doesn't work.
Maybe I should just give up using SINQ...

**Comment by slazyk** [comment]
master now compiles without problems on 7.3

**Comment by marchy** [comment]
Woohoo!! Thanks so much for this Slazyk. Time to upgrade those Xcodes!

**Comment by hazama-yuinyan** [comment]
@slazyk 

Thank you for the quick fix!
But with CocoaPods, I can't update the library!
Did you forget to update the Cocoa pods' spec file?

Please don't leave us behind you ;(

**Comment by slazyk** [comment]
Done. Update to 0.6.0 version of the pod if you are using Swift 2.2.

**Comment by hazama-yuinyan** [comment]
@slazyk 

Thank you very much for the quick response!
It works!
Yay ;)
