### ISSUE TITLE
Support for Swift 2.3 / 3.0

### ISSUE THREAD

**Issue by marchy** [slazyk/SINQ#9]
Any ETA on support for Swift 2.3/3.0?

Right now when you include the pod you have to go through a manual conversion process of the code to the new syntax. If code-level breakages are a must perhaps we could keep a separate branch for the Swift 2.2 codebase and move the new one to 2.3/3.0.

**Comment by marchy** [comment]
Any updates on this? Or is this library no longer active? This is currently blocking migration to iOS 10 and all the important features that come with it (iMessage/Maps integration, unified contacts SDK etc.)

Please let us know if you have any plans to migrate the framework (very soon) otherwise we need to look at removing this from out codebase – and it's currently in a LOT of places. Big thanks!!

**Comment by slazyk** [comment]
Hey, sorry for the delay. Just merged the pull request updating to Swift 3.

**Comment by marchy** [comment]
Thanks a lot for that @slazyk. And for making the library active again  :)
